config/routes.rb
Rails.application.routes.draw do
  resources :jyoto_eki_meisais
  resources :torihiki_rirekis
  resources :kigyo_masters
  resources :diaries
  
  # 各アップロード画面
  get 'csv_upload/index', to: "csv_upload#index"
  get 'csv_upload/index_torihiki', to: "csv_upload#index_torihiki"
  get 'csv_upload/index_jyo_to_eki', to: "csv_upload#index_jyo_to_eki"

  # 取引履歴集計 画面
  get 'son_eki', to: 'son_eki#index'
 
  # 譲渡益集計 画面
  get 'jyoto_eki_syukei', to: 'jyoto_eki_syukei#index'

  # ユーザ画面
  get 'users', to: 'users#index'
  get 'users/new', to: 'users#new'

  # CSVアップロード（更新処理）
  post "/csv_upload"=> "csv_upload#csv_import" 

  # ホーム画面
  get 'home/index', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/jyoto_eki_meisai2020.rb
class JyotoEkiMeisai2020 < ApplicationRecord

 
end

app/models/jyoto_eki_meisai2021.rb
class JyotoEkiMeisai2021 < ApplicationRecord

 
end

app/models/jyoto_eki_meisai2022.rb
class JyotoEkiMeisai2022 < ApplicationRecord

 
end

app/models/jyoto_eki_syukei.rb
class JyotoEkiSyukei 
    # 譲渡益明細ＤＢから銘柄毎の損益を算出する
  def self.get_soneki(nen)
    # 日付の組み立て
    from_date = nen + "-01-01"
    to_date = nen + "-12-31"

    case nen
    when "2020" then
      table_name = "jyoto_eki_meisai2020s "
    when "2021" then
      table_name = "jyoto_eki_meisai2021s "
    when "2022" then
      table_name = "jyoto_eki_meisai2022s "
    end

    # SQL
    query = "SELECT code, MAX(name) as name, SUM(son_eki_gaku) as son_eki_gaku, " 
    query += "MIN(yakujo_bi) AS kaituke_bi, MAX(yakujo_bi) AS baikyaku_bi "
    query += "FROM " + table_name
    query += "WHERE ukewatasi BETWEEN ? and ?"
    query += "GROUP BY code "
    query += "ORDER BY son_eki_gaku DESC "

    # 該当の証券コード毎に「株式現物買」の金額を取得する
    ret = JyotoEkiMeisai2020.find_by_sql([query, from_date, to_date])
  end

 # 譲渡益明細ＤＢから利益額合計、損失額合計、全体の損益を算出する
  def self.get_total_soneki(nen)
    # 日付の組み立て
    from_date = nen + "-01-01"
    to_date = nen + "-12-31"
   
    case nen
    when "2020" then
      table_name = "jyoto_eki_meisai2020s "
    when "2021" then
      table_name = "jyoto_eki_meisai2021s "
    when "2022" then
      table_name = "jyoto_eki_meisai2022s "
    end

    # SQL
    query = "SELECT SUM(son_eki_gaku) AS son_eki_gaku "
    query += "FROM " + table_name 
    query += "WHERE son_eki_gaku >= 0 "
    query += "AND ukewatasi BETWEEN ? AND ? "     
    query += "UNION "
    query += "SELECT SUM(son_eki_gaku) AS son_eki_gaku "
    query += "FROM " + table_name
    query += "WHERE son_eki_gaku < 0 "
    query += "AND ukewatasi BETWEEN ? AND ? " 
    query += "UNION "
    query += "SELECT SUM(son_eki_gaku) AS son_eki_gaku "
    query += "FROM " + table_name
    query += "WHERE ukewatasi BETWEEN ? AND ? " 
   
    ret = JyotoEkiMeisai2020.find_by_sql([query, from_date, to_date, from_date, to_date, from_date, to_date])

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_upload_controller.rb
class CsvUploadController < ApplicationController
  include CsvImport

  # 企業マスタアップロード画面
  def index
  end

  # 取引履歴アップロード画面
  def index_torihiki
  end

  # 譲渡益明細アップロード画面
  def index_jyo_to_eki
  end


  #CSV UpladしDBへ登録する
  def csv_import
    # 取引履歴ＣＳＶの場合
    if params[:gamen_kind] == "tori"
      @errors = import(params[:file],"tori")
      redirect_to action: 'index_torihiki' 
    # 譲渡益明細CSVの場合
    elsif params[:gamen_kind] == "jyoto"
      @errors = import(params[:file],"jyoto", params[:nendo])
      redirect_to action: 'index_jyo_to_eki' 
    # 企業マスタCSVの場合
    elsif params[:gamen_kind] == "kigyo"
      @errors = import(params[:file],"kigyo")
      redirect_to action: 'index' 
    else
      p "gamen_kind parameter eror"  
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # HOME画面
  def index

  end



end

app/controllers/jyoto_eki_syukei_controller.rb
class JyotoEkiSyukeiController < ApplicationController


  def index
    # 画面表示用
    @nen = params[:nen]

    # 銘柄毎の損益集計処理の呼び出し
    @jyoto_eki_syukeis = JyotoEkiSyukei.get_soneki(params[:nen])
    
    # 利益額合計、損失額合計、全体の損益を算出
    @total_soneki = JyotoEkiSyukei.get_total_soneki(params[:nen])
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_upload_helper.rb
module CsvUploadHelper
end

app/helpers/jyoto_eki_meisais_helper.rb
module JyotoEkiMeisaisHelper
end

app/views/csv_upload/index_jyo_to_eki.html.erb
<h1>譲渡益明細アップロード</h1>

<%= form_with url: "/csv_upload" do |form| %>

  <%= form.select :nendo, [["2020年", "2020"], ["2021年", "2021"], ["2022年", "2022"]], include_blank: "選択して下さい" %>
  <br><br>

  <%= form.hidden_field :gamen_kind, :value => "jyoto" %>
  <%= form.file_field :file, accept: '.csv' %>
  <%= form.submit "アップロード" %>

  <% if @errors.present? %>
   <% @errors.each do |error| %>
     <% error[:messages].each do |message| %>
       <li><%= "#{error[:row_num]}行目：#{message}" %></li>
     <% end %>
   <% end %>
  <% end %>

<% end %>

app/views/home/index.html.erb
<br><hr>
<menu>
  <li><a href="http://192.168.56.2:3000/csv_upload/index_jyo_to_eki">譲渡益明細アップロード</a>
</menu>
<br><hr>
<menu>
  <li><a href="http://192.168.56.2:3000/jyoto_eki_syukei?nen=2022">譲渡益明細集計</a>
</menu>

<br>
■使い方<br>
1. csvを成形し不要な行を取り除く<br>
2. CSVのヘッダーをＤＢカラム（英語）に差し替える<br>
3. CSVをエディタで開き、UTF8Nで保存する<br>
4. 画面からアップロードをする<br>

app/views/jyoto_eki_syukei/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>譲渡益集計</h1>
<h3>（受渡日：<font color = "red"><%= @nen %></font>年01月01日～
<font color = "red"><%= @nen %></font>年12月31日）</h3><br>

<table border="1">
  <% i = 0 %>
  <% @total_soneki.each do |total_soneki| %>
    <% i = i + 1 %>
    <% if i == 1 %><th>利益計</th><% end %>
    <% if i == 2 %><th>損失計</th><% end %>
    <% if i == 3 %><th>全体合計</th><% end %>
    <td><%= number_with_delimiter(total_soneki.son_eki_gaku) %></td>
  <% end %>
</table>
<br>
<%= link_to "2020年", jyoto_eki_syukei_path(nen: "2020") %> 
<%= link_to "2021年", jyoto_eki_syukei_path(nen: "2021") %> 
<%= link_to "2022年", jyoto_eki_syukei_path(nen: "2022") %> 
<table border="1">
  <thead>
    <tr>
      <th>順位</th>
      <th>コード</th>
      <th>会社名</th>
      <th>損益額</th>
      <th>買付日</th>
      <th>売却日</th>
    </tr>
    </thead>

<% if @jyoto_eki_syukeis != nil %>
  <div id="son_ekis">
    <% i = 0 %>
    <% @jyoto_eki_syukeis.each do |jyoto_eki| %>
      <tr>
        <% i = i + 1 %>
        <td><%= i %></td>
        <td><%= jyoto_eki.code %></td>
        <td><%= jyoto_eki.name %></td>
        <td>
          <% if jyoto_eki.son_eki_gaku < 0 %>
            <font color = "red">
          <% end %>
          <%= number_with_delimiter(jyoto_eki.son_eki_gaku) %>
          <% if jyoto_eki.son_eki_gaku < 0 %>
            </font>
          <% end %>
        </td>
        <td><%= jyoto_eki.kaituke_bi %></td>
        <td><%= jyoto_eki.baikyaku_bi %></td>
      </tr>
    <% end %>
  </div>      
<% end %>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SBI譲渡益集計</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class ="diary_header">
      <a href="http://192.168.56.2:3000/home/index">ホーム</a>
    </div>
    <div class ="diary_body">
      <%= yield %> 
    </div>

    <div class="diary_fotter">
      <fotter>フッター</footer>
    </div> 
  </body>
</html>